Add validation during training
- it is possible to select validation sample from the training set
during training to monitor accuracy (single possible metric)

Signed-off-by: Marek Cermak <macermak@redhat.com>

modified:   RUN
modified:   src/bin/main.cpp
modified:   src/model/model.cpp
modified:   src/model/model.h
modified:   src/ops/ops.cpp

diff --git a/RUN b/RUN
--- a/RUN
+++ b/RUN
@@ -4,26 +4,34 @@
 # TRAINING
 # ---
 
-export LOSS="categorical_cross_entropy"
+export CONTINUE_TRAINING=0
 
-export TRAIN_EPOCHS=3
+export LOSS="categorical_cross_entropy" 
+
+export TRAIN_EPOCHS=30
 export BATCH_SIZE=30
-export LEARNING_RATE=3.0
 
+export LEARNING_RATE=3.0
 export MOMENTUM_FACTOR=0.25
 
 export LOG_STEP_COUNT_STEPS=20000  # monitor thoroughly
-export SAVE_CHECKPOINT_STEP=60000  # once per epoch
+export VALIDATE_STEP_COUNT_EPOCHS=5
 
-### run training
+export SAVE_CHECKPOINT_STEP=60000  # once per epoch
+export KEEP_CHECKPOINTS_MAX=3
+
 ./mnist
 
+if [ $? -ne 0 ]; then
+	echo "Unexpected error occured during training\n"
+	exit 42
+fi
 
 # ---
 # EVALUATION && EXPORT
 # ---
+
 export SAVE_TRAIN_PREDICTIONS="trainPredictions"
 export SAVE_TEST_PREDICTIONS="actualTestPredictions"
 
-### run evaluation
 ./mnist-evaluate
